services:
  - type: web
    name: shippinggo
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      # سيقوم الأبلكيشن الآن بسحب باقي البيانات من المتغيرات التي أضفتها أنت مسبقاً
      # MYSQL_ADDON_HOST, MYSQL_ADDON_PORT, MYSQL_ADDON_DB, MYSQL_ADDON_USER, MYSQL_ADDON_PASSWORD
